import type { GeneratedConfig, ResolvedRule, RuleValue } from "../types.js";

export function generateConfigFile(config: GeneratedConfig): string {
  const lines: string[] = [
    "// ESLint Configuration",
    `// Generated by project-doctor with presets: ${config.presets.join(", ")}`,
    "",
  ];

  // Imports
  const hasTypescript = config.plugins.includes("@typescript-eslint");
  const hasStylistic = config.plugins.includes("@stylistic");

  if (hasTypescript) {
    lines.push("import tseslint from 'typescript-eslint';");
  } else {
    lines.push("import eslint from '@eslint/js';");
  }

  if (hasStylistic) {
    lines.push("import stylistic from '@stylistic/eslint-plugin';");
  }

  lines.push("", "export default [");

  // Base config spread
  if (hasTypescript) {
    if (config.requiresTypeChecking) {
      lines.push("  ...tseslint.configs.recommendedTypeChecked,");
    } else {
      lines.push("  ...tseslint.configs.recommended,");
    }
  } else {
    lines.push("  eslint.configs.recommended,");
  }

  // Stylistic plugin config
  if (hasStylistic) {
    lines.push("  stylistic.configs['recommended-flat'],");
  }

  // Custom rules block
  lines.push("  {");

  // Language options for type-checked linting
  if (config.requiresTypeChecking) {
    lines.push("    languageOptions: {", "      parserOptions: {", "        projectService: true,", "      },", "    },");
  }

  lines.push("    rules: {");

  // Add rules grouped by plugin
  const coreRules = config.rules.filter((r) => !r.name.includes("/"));
  const tsRules = config.rules.filter((r) => r.name.startsWith("@typescript-eslint/"));
  const stylisticRules = config.rules.filter((r) => r.name.startsWith("@stylistic/"));

  if (coreRules.length > 0) {
    lines.push("      // Core ESLint rules");
    for (const rule of coreRules) {
      lines.push(...formatRule(rule));
    }
    lines.push("");
  }

  if (tsRules.length > 0) {
    lines.push("      // TypeScript rules");
    for (const rule of tsRules) {
      lines.push(...formatRule(rule));
    }
    lines.push("");
  }

  if (stylisticRules.length > 0) {
    lines.push("      // Stylistic rules");
    for (const rule of stylisticRules) {
      lines.push(...formatRule(rule));
    }
  }

  lines.push("    },", "  },", "];", "");

  return lines.join("\n");
}

function formatRule(rule: ResolvedRule): string[] {
  const lines: string[] = [];
  const valueStr = formatRuleValue(rule.value);

  if (rule.comment) {
    lines.push(`      // ${rule.comment}`);
  }
  lines.push(`      "${rule.name}": ${valueStr},`);

  return lines;
}

function formatRuleValue(value: RuleValue): string {
  if (typeof value === "string") {
    return `"${value}"`;
  }
  return JSON.stringify(value);
}

export function generateMinimalConfig(hasTypescript: boolean): string {
  const lines: string[] = [ "// ESLint Configuration", ""];


  if (hasTypescript) {
    lines.push("import tseslint from 'typescript-eslint';", "", "export default tseslint.configs.recommended;");
  } else {
    lines.push("import eslint from '@eslint/js';", "", "export default [eslint.configs.recommended];");
  }

  lines.push("");
  return lines.join("\n");
}
